"""
shared/models.py — Shared Pydantic Models V5.1
All domain models used across modules. Single source of truth.

V5.1 additions:
  - LLM Structured Output models (HookOutput, CreativeOutput, BrandStrategyOutput)
  - AdsDecision model for kill-switch engine
  - ProductEvaluation model for DecisionEngine
"""
from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime


class Tenant(BaseModel):
    id: Optional[str] = None
    name: str
    billing_plan: str = "starter"
    llm_quota: dict = Field(default_factory=lambda: {"monthly_usd_limit": 100})
    settings: dict = Field(default_factory=dict)


class Opportunity(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    name: str
    niche: str
    source: str = "oracle_v4"
    score: float = 0.0
    score_breakdown: dict = Field(default_factory=dict)
    viral_score: float = 50.0
    saturation_score: float = 0.0
    status: str = "detected"
    fail_fast_spend_usd: float = 0.0
    raw_data: dict = Field(default_factory=dict)


class Campaign(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    opportunity_id: str
    platform: str                  # tiktok | meta | google | amazon | mercadolibre
    external_campaign_id: Optional[str] = None
    budget_usd: float
    spend_usd: float = 0.0
    revenue_usd: float = 0.0
    roas: Optional[float] = None
    impressions: int = 0
    clicks: int = 0
    conversions: int = 0
    ctr: Optional[float] = None
    cpa: Optional[float] = None
    status: str = "active"         # active | paused | killed | completed
    started_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None


class Hook(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    hook_text: str
    category: str                  # fear|curiosity|scarcity|transformation|social_proof|identity|savings
    niche: Optional[str] = None
    avg_ctr: Optional[float] = None
    test_count: int = 0
    winning_count: int = 0
    metadata: dict = Field(default_factory=dict)


class Brand(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    opportunity_id: str
    name: str
    strategy: dict = Field(default_factory=dict)
    visual_identity: dict = Field(default_factory=dict)
    store_url: Optional[str] = None
    status: str = "pending"        # pending | approved | live


class Product(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    brand_id: str
    name: str
    sku: Optional[str] = None
    price_usd: Optional[float] = None
    cogs_usd: Optional[float] = None
    margin_pct: Optional[float] = None
    description: Optional[str] = None
    images: list = Field(default_factory=list)
    status: str = "draft"


class SaturationLog(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    campaign_id: str
    delta_cpm: float
    new_competitors: int
    delta_ctr: float
    saturation_score: float
    hazard_prob: float
    action_taken: str


class AllocationRun(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    total_budget_usd: float
    allocations: dict              # {campaign_id: budget_usd}
    product_stats: dict = Field(default_factory=dict)
    rationale: str = ""


class DecisionLog(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    entity_type: str               # opportunity | campaign | brand | niche
    entity_id: Optional[str] = None
    action: str                    # kill | approve | scale | hold | alert
    trigger: str = "auto"          # auto | human_gate | timeout
    reason: str = ""
    data: dict = Field(default_factory=dict)


class NicheProfile(BaseModel):
    id: Optional[str] = None
    tenant_id: str
    anchor_opportunity_id: str
    niche_name: str
    anchor_product: str
    complementary_products: list = Field(default_factory=list)
    consolidated_brand_id: Optional[str] = None
    swarm_status: str = "in_progress"  # in_progress | dominated | saturating
    combined_roas: Optional[float] = None


# ═══════════════════════════════════════════════════════════════════════════════
# V5.1 — LLM STRUCTURED OUTPUT MODELS
# Used with OpenAI Structured Outputs API + Pydantic validation
# Eliminates regex JSON parsing entirely for LLM responses
# ═══════════════════════════════════════════════════════════════════════════════

class HookOutput(BaseModel):
    """Single TikTok/Meta hook generated by Creative Engine."""
    hook_type: Literal["fear", "transformation", "social_proof", "curiosity", "urgency"]
    hook_text: str = Field(..., max_length=150, description="Hook text <5 seconds")
    script: str = Field(..., max_length=1500, description="Full 30s TikTok script")
    cta: str = Field(..., max_length=100, description="Call to action text")
    estimated_ctr: float = Field(..., ge=0.0, le=1.0, description="Estimated CTR 0-1")
    pain_point_addressed: str = Field(default="", max_length=200)


class CreativeOutput(BaseModel):
    """Structured output from Creative Intelligence Engine."""
    hooks: List[HookOutput] = Field(..., min_length=1, max_length=5)
    product_positioning: str = Field(default="", max_length=300)
    target_audience: str = Field(default="", max_length=200)


class BrandStrategyOutput(BaseModel):
    """Structured brand strategy from BrandCreator."""
    name: str = Field(..., max_length=30)
    tagline: str = Field(..., max_length=80)
    values: List[str] = Field(..., min_length=3, max_length=3)
    voice: str = Field(..., max_length=100)
    positioning: str = Field(..., max_length=300)
    color_palette: List[str] = Field(default_factory=list, max_length=5)
    target_demo: str = Field(default="", max_length=200)


class DiscoverySignal(BaseModel):
    """Product trend signal from Discovery Engine."""
    product_name: str = Field(..., max_length=200)
    niche: str = Field(..., max_length=100)
    trend_source: Literal["tiktok", "amazon", "google_trends", "meta_library"]
    viral_score: float = Field(..., ge=0.0, le=100.0)
    estimated_demand: float = Field(..., ge=0.0, le=100.0)
    competition_level: Literal["low", "moderate", "high", "saturated"]
    pain_points: List[str] = Field(default_factory=list, max_length=5)
    raw_data: dict = Field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════════════════════
# V5.1 — ENGINE DECISION MODELS
# ═══════════════════════════════════════════════════════════════════════════════

class AdsDecision(BaseModel):
    """Decision output from AdsDecisionEngine kill-switch."""
    action: Literal["SCALE", "HOLD", "KILL"]
    reason: str = Field(..., max_length=300)
    roas: float = Field(..., ge=0.0)
    spend_usd: float = Field(..., ge=0.0)
    revenue_usd: float = Field(..., ge=0.0)
    budget_change_pct: float  # +20 = scale 20%, 0 = hold, -100 = kill
    campaign_id: str = Field(default="", max_length=64)
    alert_sent: bool = False
    decided_at: Optional[datetime] = None


class ProductEvaluation(BaseModel):
    """Evaluation output from core DecisionEngine."""
    decision: Literal["launch_test", "reject", "manual_review"]
    reason: str = Field(default="", max_length=300)
    score: float = Field(..., ge=0.0, le=100.0)
    budget_usd: float = Field(default=0.0, ge=0.0)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    product_id: str = Field(default="", max_length=64)
    product_name: str = Field(default="", max_length=200)


class OrchestratorCycleResult(BaseModel):
    """Result of a full autonomous orchestration cycle."""
    cycle_id: str = Field(..., max_length=64)
    tenant_id: str = Field(..., max_length=64)
    niches_processed: int = 0
    signals_found: int = 0
    products_scored: int = 0
    products_approved: int = 0
    products_rejected: int = 0
    creative_hooks_generated: int = 0
    ads_decisions: List[AdsDecision] = Field(default_factory=list)
    total_budget_allocated_usd: float = 0.0
    duration_seconds: float = 0.0
    errors: List[str] = Field(default_factory=list)
